# Generated by Django 5.1.6 on 2025-09-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(choices=[('ON', 'Bật'), ('OFF', 'Tắt')], max_length=3),
        ),
    ]
