# Generated by Django 5.1.6 on 2025-11-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_action_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasensor',
            name='air',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
