# Generated by Django 5.1.6 on 2025-11-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_datasensor_air'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasensor',
            name='air',
        ),
    ]
